# Generated by Django 4.1.4 on 2023-05-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='sessions',
            field=models.ManyToManyField(related_name='levels', to='main.session'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='levels',
            field=models.ManyToManyField(related_name='semesters', to='main.level'),
        ),
        migrations.AlterField(
            model_name='session',
            name='department',
            field=models.ManyToManyField(related_name='sessions', to='main.department'),
        ),
    ]
