# Generated by Django 4.2.1 on 2023-05-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_level_sessions_alter_semester_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
